"""empty message

Revision ID: ac7de73b19a3
Revises: 69773f5d79fe
Create Date: 2019-07-11 10:59:14.054901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7de73b19a3'
down_revision = '69773f5d79fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'forms', ['form_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forms', type_='unique')
    # ### end Alembic commands ###
